Repository Ivy-Apps/ivy-wallet, pull requests merged in 2024-09, with the labels that each got.

#3444 fix csv export
  shared/base/src/main/java/com/ivy/base/time/impl/TestTimeConverter.kt
  shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt
  shared/domain/src/test/java/com/ivy/domain/usecase/csv/ExportCsvUseCasePropertyTest.kt
Labels: requested changes

#3466 feat: Add toggle for showing previous title suggestions in transactio…
  screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
  screen/planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedScreen.kt
  shared/domain/src/main/java/com/ivy/domain/features/BoolFeature.kt
  shared/domain/src/main/java/com/ivy/domain/features/Features.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/Title.kt
Labels: requested changes, ready to merge 🚀

#3476 fix-issue-3438
  screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
Labels: requested changes

#3482 fix-issue-3481
  app/src/main/java/com/ivy/wallet/RootActivity.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenEvent.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenState.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
  screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt
  screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreenState.kt
  screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt
  screen/loans/src/main/java/com/ivy/loans/loandetails/events/LoanModalEvent.kt
  screen/loans/src/main/java/com/ivy/loans/loandetails/events/LoanRecordModalEvent.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt
Labels: requested changes

#3499 Search Functionality In Category Screen
  screen/categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
  screen/categories/src/main/java/com/ivy/categories/CategoriesScreenEvent.kt
  screen/categories/src/main/java/com/ivy/categories/CategoriesScreenState.kt
  screen/categories/src/main/java/com/ivy/categories/CategoriesViewModel.kt
  screen/categories/src/test/java/com/ivy/categories/CategoriesScreenPaparazziTest.kt
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen with search bar[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen with search bar[Light].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen[Light].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen with search bar[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen with search bar[Light].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen[Light].png
  shared/domain/src/main/java/com/ivy/domain/features/Features.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/ui/SearchInput.kt
Labels: requested changes

#3508 BottomBar added on Exchange Rates Screen
  screen/exchange-rates/src/main/java/com/ivy/exchangerates/ExchangeRateBottomBar.kt
  screen/exchange-rates/src/main/java/com/ivy/exchangerates/ExchangeRatesScreen.kt
  screen/exchange-rates/src/test/snapshots/images/com.ivy.exchangerates_ExchangeRatesScreenPaparazziTest_snapshot Exchange Rates Screen[Dark].png
  screen/exchange-rates/src/test/snapshots/images/com.ivy.exchangerates_ExchangeRatesScreenPaparazziTest_snapshot Exchange Rates Screen[Light].png
  shared/ui/core/src/main/res/values-ar/strings.xml
  shared/ui/core/src/main/res/values-bg/strings.xml
  shared/ui/core/src/main/res/values-de/strings.xml
  shared/ui/core/src/main/res/values-es/strings.xml
  shared/ui/core/src/main/res/values-hi/strings.xml
  shared/ui/core/src/main/res/values-id/strings.xml
  shared/ui/core/src/main/res/values-in/strings.xml
  shared/ui/core/src/main/res/values-it/strings.xml
  shared/ui/core/src/main/res/values-kn/strings.xml
  shared/ui/core/src/main/res/values-mn/strings.xml
  shared/ui/core/src/main/res/values-pl/strings.xml
  shared/ui/core/src/main/res/values-pt-rBR/strings.xml
  shared/ui/core/src/main/res/values-ru/strings.xml
  shared/ui/core/src/main/res/values-vi/strings.xml
  shared/ui/core/src/main/res/values-zh-rCN/strings.xml
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
  shared/ui/core/src/main/res/values/strings.xml
Labels: requested changes

#3517 Refactor: Use 'by' delegation for mutableStateOf properties
  screen/home/src/main/java/com/ivy/home/HomeViewModel.kt
Labels: ready to merge 🚀

#3524 [Refactor] BalanceViewModel: using by delegation for mutable states
  screen/balance/src/main/java/com/ivy/balance/BalanceViewModel.kt
Labels: ready to merge 🚀

#3525 [Refactor] AccountsViewModel: using by delegation for mutable states
  screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
Labels: ready to merge 🚀

#3531 [Refactor] PlannedPaymentsViewModel: using by delegation for mutable states
  screen/planned-payments/src/main/java/com/ivy/planned/list/PlannedPaymentsViewModel.kt
Labels: ready to merge 🚀

#3532 fix-issue-3515
  screen/exchange-rates/src/main/java/com/ivy/exchangerates/ExchangeRatesScreen.kt
  screen/exchange-rates/src/test/snapshots/images/com.ivy.exchangerates_ExchangeRatesScreenPaparazziTest_snapshot Exchange Rates Screen[Dark].png
  screen/exchange-rates/src/test/snapshots/images/com.ivy.exchangerates_ExchangeRatesScreenPaparazziTest_snapshot Exchange Rates Screen[Light].png
Labels: ready to merge 🚀

#3539 Tabular Loan UI added
  screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenEvent.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenMode.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenState.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanTab.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt
  screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
  screen/loans/src/main/java/com/ivy/loans/loan/NonTabularLoanBottomBar.kt
  screen/loans/src/main/java/com/ivy/loans/loan/TabularLoanBottomBar.kt
  screen/loans/src/test/java/com/ivy/loans/LoanScreenPaparazziTest.kt
  screen/loans/src/test/snapshots/images/com.ivy.loans_LoanScreenPaparazziTest_snapshot loanScreen non tabular composable[Dark].png
  screen/loans/src/test/snapshots/images/com.ivy.loans_LoanScreenPaparazziTest_snapshot loanScreen non tabular composable[Light].png
  screen/loans/src/test/snapshots/images/com.ivy.loans_LoanScreenPaparazziTest_snapshot loanScreen tabular composable[Dark].png
  screen/loans/src/test/snapshots/images/com.ivy.loans_LoanScreenPaparazziTest_snapshot loanScreen tabular composable[Light].png
  shared/domain/src/main/java/com/ivy/domain/features/Features.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/IvyWalletCtx.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/IvyColors.kt
Labels: requested changes

#3538 Create True Black mode for amoled screens
  screen/home/src/main/java/com/ivy/home/HomeMoreMenu.kt
  screen/settings/src/main/java/com/ivy/settings/SettingsScreen.kt
  shared/base/src/main/java/com/ivy/base/legacy/Theme.kt
  shared/ui/core/src/main/java/com/ivy/design/system/IvyMaterial3Theme.kt
  shared/ui/core/src/main/java/com/ivy/design/system/colors/IvyColors.kt
  shared/ui/core/src/main/res/drawable/home_more_menu_amoled_dark_mode.xml
  shared/ui/core/src/main/res/values/strings.xml
  shared/ui/core/src/test/java/com/ivy/ui/PaparazziScreenshotTest.kt
  shared/ui/navigation/src/main/java/com/ivy/navigation/IvyPreview.kt
  shared/ui/testing/src/main/java/com/ivy/ui/testing/PaparazziScreenshotTest.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/settings/SettingsAct.kt
  temp/old-design/src/main/java/com/ivy/design/api/systems/IvyWalletDesign.kt
  temp/old-design/src/main/java/com/ivy/design/l0_system/Colors.kt
  temp/old-design/src/main/java/com/ivy/design/l0_system/IvyTheme.kt
Labels: requested changes

#3551 zh_TW translation correction
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
Labels: ready to merge 🚀

#3563 [FEATURE] Advanced features grouping
  screen/features/src/main/java/com/ivy/features/FeaturesScreen.kt
  screen/features/src/main/java/com/ivy/features/FeaturesUiEvent.kt
  screen/features/src/main/java/com/ivy/features/FeaturesUiState.kt
  screen/features/src/main/java/com/ivy/features/FeaturesViewModel.kt
  shared/domain/src/main/java/com/ivy/domain/features/BoolFeature.kt
  shared/domain/src/main/java/com/ivy/domain/features/FeatureGroup.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
Labels: requested changes

#3569 zh_TW translation correction
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
Labels: ready to merge 🚀

#3570 Fix #3432 Recurring expenses spawn at UTC timing instead of local time
  temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/viewmodel/home/DueTrnsInfoAct.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/RecurringRuleModal.kt
Labels: ready to merge 🚀
