Repository Ivy-Apps/ivy-wallet, pull requests merged in 2024-07, with the labels that each got.

#3262 Fix issue 3252
  screen/import-data/src/main/java/com/ivy/importdata/csv/domain/ParseFields.kt
Labels: requested changes

#3269 Fix issue #3133
  .gitignore
  docs/Guidelines.md
  docs/guidelines/Architecture.md
  docs/guidelines/Data-Modeling.md
  docs/guidelines/Error-Handling.md
  docs/guidelines/Screen-Architecture.md
  docs/guidelines/Unit-Testing.md
Labels: keep, requested changes

#3306 Issue 3270 - CONTRIBUTING.md fixes and readability enhancements
  CONTRIBUTING.md
Labels: keep

#3307 Added zh_TW translation
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
Labels: requested changes, ready to merge 🚀

#3319 PR template readability and standardization fixes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: keep

#3324 Different decimal place for crypto and fiat currency
  temp/legacy-code/src/main/java/com/ivy/legacy/domain/data/IvyCurrency.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/CustomExchangeRateCard.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/EditBottomSheet.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt
Labels: requested changes

#3329 Added the tonchain currency
  temp/legacy-code/src/main/java/com/ivy/legacy/domain/data/IvyCurrency.kt
Labels: ready to merge 🚀

#3330 Remove the library that causing 3328
  gradle/libs.versions.toml
Labels: requested changes

#3333 Removed all code related to sign in through google from app.
  app/build.gradle.kts
  app/src/main/java/com/ivy/IvyNavGraph.kt
  app/src/main/java/com/ivy/wallet/RootActivity.kt
  app/src/main/java/com/ivy/wallet/RootViewModel.kt
  app/src/main/java/com/ivy/wallet/migrations/MigrationsManager.kt
  app/src/main/java/com/ivy/wallet/ui/applocked/AppLockedScreen.kt
  config/detekt/baseline.yml
  config/detekt/config.yml
  gradle/libs.versions.toml
  screen/onboarding/src/main/java/com/ivy/onboarding/OnboardingEvent.kt
  screen/onboarding/src/main/java/com/ivy/onboarding/steps/OnboardingSplashLogin.kt
  screen/onboarding/src/main/java/com/ivy/onboarding/viewmodel/OnboardingViewModel.kt
Labels: requested changes

#3337 Fix issue 3138
  screen/settings/src/main/java/com/ivy/settings/SettingsEvent.kt
  screen/settings/src/main/java/com/ivy/settings/SettingsScreen.kt
  screen/settings/src/main/java/com/ivy/settings/SettingsState.kt
  screen/settings/src/main/java/com/ivy/settings/SettingsViewModel.kt
  shared/ui/core/src/main/res/values-ar/strings.xml
  shared/ui/core/src/main/res/values-bg/strings.xml
  shared/ui/core/src/main/res/values-de/strings.xml
  shared/ui/core/src/main/res/values-es/strings.xml
  shared/ui/core/src/main/res/values-hi/strings.xml
  shared/ui/core/src/main/res/values-id/strings.xml
  shared/ui/core/src/main/res/values-in/strings.xml
  shared/ui/core/src/main/res/values-it/strings.xml
  shared/ui/core/src/main/res/values-kn/strings.xml
  shared/ui/core/src/main/res/values-mn/strings.xml
  shared/ui/core/src/main/res/values-pl/strings.xml
  shared/ui/core/src/main/res/values-pt-rBR/strings.xml
  shared/ui/core/src/main/res/values-ru/strings.xml
  shared/ui/core/src/main/res/values-vi/strings.xml
  shared/ui/core/src/main/res/values-zh-rCN/strings.xml
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
  shared/ui/core/src/main/res/values/strings.xml
Labels: requested changes

#3351 Change dateNowUTC() to dateNowLocal() because dateNowUTC() giving wrong date
  temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/HistoryDateDivider.kt
Labels: Missing PR description

#3368 feat: Add "Total Remaining Budget" display
  screen/budgets/src/main/java/com/ivy/budgets/BudgetScreen.kt
  screen/budgets/src/main/java/com/ivy/budgets/BudgetScreenState.kt
  screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
  shared/ui/core/src/main/res/values-ar/strings.xml
  shared/ui/core/src/main/res/values-bg/strings.xml
  shared/ui/core/src/main/res/values-de/strings.xml
  shared/ui/core/src/main/res/values-es/strings.xml
  shared/ui/core/src/main/res/values-hi/strings.xml
  shared/ui/core/src/main/res/values-id/strings.xml
  shared/ui/core/src/main/res/values-in/strings.xml
  shared/ui/core/src/main/res/values-it/strings.xml
  shared/ui/core/src/main/res/values-kn/strings.xml
  shared/ui/core/src/main/res/values-mn/strings.xml
  shared/ui/core/src/main/res/values-pl/strings.xml
  shared/ui/core/src/main/res/values-pt-rBR/strings.xml
  shared/ui/core/src/main/res/values-ru/strings.xml
  shared/ui/core/src/main/res/values-vi/strings.xml
  shared/ui/core/src/main/res/values-zh-rCN/strings.xml
  shared/ui/core/src/main/res/values-zh-rTW/strings.xml
  shared/ui/core/src/main/res/values/strings.xml
Labels: requested changes
