Repository Ivy-Apps/ivy-wallet, pull requests merged in 2024-08, with the labels that each got.

#3381 Fix issue 3370
  buildSrc/src/main/kotlin/ivy.script.gradle.kts
  gradle/libs.versions.toml
  screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt
  screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt
  screen/contributors/src/test/java/com/ivy/contributors/ContributorsViewModelTest.kt
Labels: Stale, requested changes

#3428 [FEATURE] Dense account design
  screen/accounts/src/main/java/com/ivy/accounts/AccountsState.kt
  screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
  screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
  screen/accounts/src/test/java/com/ivy/accounts/AccountsTabPaparazziTest.kt
  screen/accounts/src/test/snapshots/images/com.ivy.accounts_AccountsTabPaparazziTest_snapshot accountTab compact composable[Dark].png
  screen/accounts/src/test/snapshots/images/com.ivy.accounts_AccountsTabPaparazziTest_snapshot accountTab compact composable[Light].png
  screen/accounts/src/test/snapshots/images/com.ivy.accounts_AccountsTabPaparazziTest_snapshot accountTab nonCompact composable[Dark].png
  screen/accounts/src/test/snapshots/images/com.ivy.accounts_AccountsTabPaparazziTest_snapshot accountTab nonCompact composable[Light].png
  shared/data/core/src/test/java/com/ivy/data/dao/FakeTransactionDaoTest.kt
  shared/domain/src/main/java/com/ivy/domain/features/Features.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
Labels: ready to merge 🚀

#3418 [Domain] Build AccountBalanceUseCase
  shared/domain/src/main/java/com/ivy/domain/usecase/BalanceBuilder.kt
  shared/domain/src/main/java/com/ivy/domain/usecase/account/AccountBalanceUseCase.kt
  shared/domain/src/test/java/com/ivy/domain/usecase/balance/BalanceBuilderTest.kt
Labels: requested changes

#3431 Fix issue 3364
  screen/categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
  screen/categories/src/main/java/com/ivy/categories/CategoriesScreenState.kt
  screen/categories/src/main/java/com/ivy/categories/CategoriesViewModel.kt
  screen/categories/src/test/java/com/ivy/categories/CategoriesScreenPaparazziTest.kt
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen[Light].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen[Dark].png
  screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories nonCompact Screen[Light].png
  shared/domain/src/main/java/com/ivy/domain/features/Features.kt
  shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
  temp/legacy-code/src/main/java/com/ivy/legacy/utils/WalletUtil.kt
Labels: requested changes

#3426 fix: removed csvFormat() and kept UTC format
  shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt
Labels: requested changes

#3450 [IVY-3445] Fix Tag Backup and Restore
  shared/data/core/src/androidTest/java/com/ivy/data/backup/BackupDataUseCaseAndroidTest.kt
  shared/data/core/src/main/java/com/ivy/data/backup/BackupDataUseCase.kt
  shared/data/core/src/main/java/com/ivy/data/backup/IvyWalletCompleteData.kt
  shared/data/core/src/test/java/com/ivy/data/backup/BackupDataUseCaseTest.kt
Labels: ready to merge 🚀
